service: serverless-line-messaging-api-endpoint

provider:
  name: aws
  runtime: nodejs6.10
  region: ap-northeast-1

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: webhook_events
          method: post
